# Generated by Django 4.1.6 on 2023-02-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountmodel",
            name="account_type",
            field=models.CharField(
                choices=[("COMMON", "Common"), ("SPECIAL", "Special")],
                default="COMMON",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="accountmodel",
            name="client_id",
            field=models.CharField(default=11111111, max_length=11),
            preserve_default=False,
        ),
    ]
