# Generated by Django 4.1.6 on 2023-02-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0002_accountmodel_account_type_accountmodel_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmodel",
            name="account_type",
            field=models.CharField(
                choices=[("COMMON", "Common"), ("SPECIAL", "Special")],
                default="COMMON",
                max_length=12,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountmodel",
            unique_together={("client_id", "account_type")},
        ),
    ]
