# Generated by Django 4.1.6 on 2023-02-02 19:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0003_alter_accountmodel_account_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmodel",
            name="account_type",
            field=models.CharField(
                choices=[("COMMON", "Common"), ("SPECIAL", "Special")],
                default="COMMON",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="LedgerModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("IN", "In"), ("OUT", "Out")], max_length=12
                    ),
                ),
                ("amount", models.FloatField(default=0.0)),
                ("description", models.TextField(blank=True, default="No description")),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ledger.accountmodel",
                    ),
                ),
            ],
        ),
    ]
