# Generated by Django 4.1.6 on 2023-02-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0004_alter_accountmodel_account_type_ledgermodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ledgermodel",
            old_name="account_type",
            new_name="ledger_type",
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="account_type",
            field=models.CharField(
                choices=[("COMMON", "Common"), ("SPECIAL", "Special")],
                default="COMMON",
                max_length=12,
            ),
        ),
    ]
